apiVersion: v1
kind: PersistentVolume
metadata:
  name: user-postgres-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/user-postgres"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: user-postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
