apiVersion: v1
kind: Service
metadata:
  name: user-postgres
  labels:
    app: user-postgres
spec:
  type: ClusterIP
  selector:
    app: user-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
